apiVersion: v1
kind: Service
metadata:
  name: lab-open5gs-mongodb
  labels:
    app: lab-open5gs-mongodb
spec:
  selector:
    app: lab-open5gs-mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-open5gs-mongodb
  labels:
    app: lab-open5gs-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-open5gs-mongodb
  template:
    metadata:
      labels:
        app: lab-open5gs-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4.29
          imagePullPolicy: IfNotPresent
          args:
            - "--bind_ip_all"
          env:
            - name: MONGO_INITDB_DATABASE
              value: open5gs
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: data
              mountPath: /data/db
      volumes:
        - name: data
          emptyDir: {}
